apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: king-rules

spec:
  rules:
  - host: "jpedro.cloud.okteto.net"
    http:
      paths:
      - backend:
          serviceName: echo
          servicePort: 80
