apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-$NUMBER
spec:
  selector:
    matchLabels:
      app: echo-$NUMBER
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-$NUMBER
    spec:
      containers:
      - name: echo
        image: jpedrob/echo
        imagePullPolicy: Always
        env:
        - name: __NUMBER__
          value: "$NUMBER"
