---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: king-rules

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: king-rules
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: king-rules
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: king-rules
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: king-rules

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: king-rules
spec:
  replicas: 1
  selector:
    matchLabels:
      app: king-rules
  template:
    metadata:
      labels:
        app: king-rules
    spec:
      serviceAccountName: king-rules
      containers:
      - name: app
        image: jpedrob/king-rules
        imagePullPolicy: Always
        env:
        # Required as this is not passed on to the container
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
