apiVersion: apps/v1
kind: Deployment
metadata:
  name: king-rules
spec:
  selector:
    matchLabels:
      app: king-rules
  replicas: 1
  template:
    metadata:
      labels:
        app: king-rules
    spec:
      serviceAccountName: king-rules
      containers:
      - name: app
        image: jpedrob/king-rules:${TAG}
        imagePullPolicy: Always
        env:
        - name: LOG_LEVEL
          value: debug
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
