---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: king-rules

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: king-rules
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: king-rules
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: king-rules
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: king-rules
