---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: king-rules

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: king-rules
rules:
# - apiGroups:
#   - ""
#   resources:
#   - pods
#   - pods/log
#   - pods/exec
#   - pods/attach
#   - pods/portforward
#   - configmaps
#   - secrets
#   - services
#   - endpoints
#   - serviceaccounts
#   - events
#   - persistentvolumeclaims
#   - replicationcontrollers
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups:
#   - ""
#   resources:
#   - events
#   - limitranges
#   - namespaces
#   - namespaces/status
#   - resourcequotas
#   - resourcequotas/status
#   verbs:
#   - get
#   - list
# - apiGroups:
#   - apps
#   resources:
#   - daemonsets
#   - deployments
#   - replicasets
#   - statefulsets
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups:
#   - extensions
#   resources:
#   - deployments
#   - ingresses
#   - replicasets
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups:
#   - extensions
#   resources:
#   - ingresses
#   verbs:
#   - update
# - apiGroups:
#   - networking.k8s.io
#   resources:
#   - ingresses
#   verbs:
#   - update
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/exec
  - pods/attach
  - pods/portforward
  - configmaps
  - secrets
  - services
  - endpoints
  - serviceaccounts
  - events
  - persistentvolumeclaims
  - replicationcontrollers
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  - limitranges
  - namespaces
  - namespaces/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - deployments
  - ingresses
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
- apiGroups:
  - helm.fluxcd.io
  resources:
  - helmreleases
  - helmreleases/status
  verbs:
  - '*'
- apiGroups:
  - helm.integrations.flux.weave.works
  resources:
  - fluxhelmreleases
  verbs:
  - '*'
- apiGroups:
  - configuration.konghq.com
  resources:
  - kongplugins
  - kongconsumers
  - kongcredentials
  - kongingresses
  - tcpingresses
  verbs:
  - '*'
- apiGroups:
  - openfaas.com
  resources:
  - functions
  verbs:
  - '*'
- apiGroups:
  - litmuschaos.io
  resources:
  - chaosengines
  - chaosexperiments
  - chaosresults
  verbs:
  - '*'
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - list
  - watch
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: king-rules
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: king-rules
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: king-rules
